name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -v

      - name: List environment dependencies
        run: pio pkg list

      - name: Add project hashes
        run: python scripts/ci_commit_hashes.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update firmware hashes from CI"
          file_pattern: "firmware_hashes.json"

      - name: Upload firmware hashes
        uses: actions/upload-artifact@v3
        with:
          name: firmware_hashes
          path: .pio/firmware_hashes.json
