name: PlatformIO CI

on: [push, pull_request]

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -v

      - name: List environment dependencies
        run: pio pkg list

      - name: Add project hashes
        run: python scripts/ci_commit_hashes.py

      - uses: EndBug/add-and-commit@v9
        with:
          add: "firmware_hashes.json"
          message: "Update firmware hashes from CI"

      - name: Upload firmware hashes
        uses: actions/upload-artifact@v3
        with:
          name: firmware_hashes
          path: .pio/firmware_hashes.json
